# Site settings
title: Gabe Weintraub 
email: gabe.weintraub+cf@gmail.com
url: https://gweintraub.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4c4d4f #18bc9c #80B3FF
  secondary: 981B1E #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Gabe Weintraub
  location:
  social: Around the Web
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/gabeweintraub
  - title: instagram
    url: https://instagram.com/gabeweintraub/
  - title: linkedin
    url: https://www.linkedin.com/in/gabeweintraub
  - title: github
    url: http://github.com/gweintraub

# Postal address (add as many lines as necessary)


# Credits content
credits: #'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
